{
  "build": "py38h0a44026_0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/osx-64",
  "constrains": [],
  "depends": [
    "libcxx >=4.0.1",
    "python >=3.8,<3.9.0a0",
    "unixodbc >=2.3.7,<2.4.0a0"
  ],
  "extracted_package_dir": "/usr/local/anaconda3/pkgs/pyodbc-4.0.30-py38h0a44026_0",
  "features": "",
  "files": [
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/INSTALLER",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/LICENSE.txt",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/METADATA",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/RECORD",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/WHEEL",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/top_level.txt",
    "lib/python3.8/site-packages/pyodbc.cpython-38-darwin.so"
  ],
  "fn": "pyodbc-4.0.30-py38h0a44026_0.conda",
  "legacy_bz2_md5": "124b6029662ae15a190efdbf9135b269",
  "legacy_bz2_size": 70510,
  "license": "MIT",
  "license_family": "MIT",
  "link": {
    "source": "/usr/local/anaconda3/pkgs/pyodbc-4.0.30-py38h0a44026_0",
    "type": 1
  },
  "md5": "9029f83330d12de3bcda06948bae18c1",
  "name": "pyodbc",
  "package_tarball_full_path": "/usr/local/anaconda3/pkgs/pyodbc-4.0.30-py38h0a44026_0.conda",
  "paths_data": {
    "paths": [
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/INSTALLER",
        "path_type": "hardlink",
        "sha256": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "sha256_in_prefix": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "size_in_bytes": 5
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/LICENSE.txt",
        "path_type": "hardlink",
        "sha256": "9859c85770c91b7866b0f769c938e36d64d0260141b529b947b4ead96883eab4",
        "sha256_in_prefix": "9859c85770c91b7866b0f769c938e36d64d0260141b529b947b4ead96883eab4",
        "size_in_bytes": 868
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/METADATA",
        "path_type": "hardlink",
        "sha256": "ab75cf0173e126f4f45ec4a1438e67e76ccd1e2fe43a023932fd7028cfaa02b1",
        "sha256_in_prefix": "ab75cf0173e126f4f45ec4a1438e67e76ccd1e2fe43a023932fd7028cfaa02b1",
        "size_in_bytes": 2134
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/RECORD",
        "path_type": "hardlink",
        "sha256": "eff76c27b6e18a3f7b8d0d508e1e157ca76eee1daf786907e309d2c3d1db091c",
        "sha256_in_prefix": "eff76c27b6e18a3f7b8d0d508e1e157ca76eee1daf786907e309d2c3d1db091c",
        "size_in_bytes": 635
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/WHEEL",
        "path_type": "hardlink",
        "sha256": "1e273806bec7caa425a3f5818962b9f14bc4a200a75a79f4d13387274314aa97",
        "sha256_in_prefix": "1e273806bec7caa425a3f5818962b9f14bc4a200a75a79f4d13387274314aa97",
        "size_in_bytes": 109
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/top_level.txt",
        "path_type": "hardlink",
        "sha256": "df48ef61c0ae97aff0036e8e4f9734ebc1801f3a902e977d59f4349924ac0d35",
        "sha256_in_prefix": "df48ef61c0ae97aff0036e8e4f9734ebc1801f3a902e977d59f4349924ac0d35",
        "size_in_bytes": 7
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc.cpython-38-darwin.so",
        "file_mode": "binary",
        "path_type": "hardlink",
        "prefix_placeholder": "/opt/concourse/worker/volumes/live/e1c2d77a-2feb-4538-7458-3a1d0c55819b/volume/pyodbc_1581353954675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol",
        "sha256": "8ab874d090b913d3f7a4aa4f7f47c7c48e38d9bd635b45bd1661b186595a8b16",
        "sha256_in_prefix": "3c7f6a867fd1f0f60f22778d029438afacd7b4fd2cd5088574d8a9ac6f4fb6fa",
        "size_in_bytes": 158368
      }
    ],
    "paths_version": 1
  },
  "requested_spec": "None",
  "sha256": "50546eca6d2433c6bfee2d1305eb1e996ecd5b8639f4ccb6f5731a7241b22261",
  "size": 65925,
  "subdir": "osx-64",
  "timestamp": 1581354030381,
  "track_features": "",
  "url": "https://repo.anaconda.com/pkgs/main/osx-64/pyodbc-4.0.30-py38h0a44026_0.conda",
  "version": "4.0.30"
}